apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: credential-access-os-credential-dumping-proc-filesystem
  namespace: multiubuntu  #use your namespace name here
spec:
  severity: 3
  selector:
    matchLabels:
      container: ubuntu-1  #use your labels name here
  file:
    matchDirectories:
      - dir: /proc/
        recursive: true
        readOnly: false
  action: BlockWithAudit
